---

- name: copy manifests to /tmp
  copy:
    src: "{{item}}"
    dest: /tmp
    mode: 0766
  with_fileglob: "*.yaml"

- name: BLOCK use older ConfigMap style for MetalLB v0.11 and earlier
  block:

    # https://metallb.universe.tf/installation/
    - name: apply metallb manifests
      k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: "/tmp/{{item}}"
      loop:
        - namespace.yaml
        - metallb-{{metallb_version}}.yaml
    
#    - name: ensure metallb-system ns exists
#      k8s:
#        state: present
#        kubeconfig: /etc/rancher/k3s/k3s.yaml
#        name: metallb-system
#        kind: Namespace

    - name: create metallb configmap
      k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            namespace: metallb-system
            name: config
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - "{{metal_lb_primary}}-{{metal_lb_secondary}}"

  when: metallb_version <= "v0.11"

- name: BLOCK use newer CRD (not Configmap) for MetalLB v0.12 and later
  block:
    # https://metallb.universe.tf/installation/
    - name: apply metallb manifests
      k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: "/tmp/{{item}}"
      loop:
        - metallb-native-{{metallb_version}}.yaml
        - metallb-ipaddresspool.yml
  when: metallb_version > "1.21"


