---

- hosts: master
  gather_facts: yes
  become: no
  tags:
    - ingress

  roles:
    # public LB endpoints
    - role: k3s-metallb

    # primary and secondary nginx ingress
    - role: add_primary_nginx_ingress
    - role: add_secondary_nginx_ingress
