---

# Our own ubuntu prereq: os packages, settings, binaries
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - k3s-prereq

# role coming from 'k3s-ansible' project
# https://github.com/k3s-io/k3s-ansible
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - prereq 
    - download
