---

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: master
  become: yes
  roles:
    - role: additional-netplan-ip
    - role: k3s-fix-master-node-ip
    - { role: k3s-get-kubeconfig-local }
    - role: k9s

- hosts: master
  become: no
  roles:
    - role: tiny-tools-all-nodes
