---

# role comes from https://github.com/k3s-io/k3s-ansible
- hosts: master
  become: yes
  roles:
    - role: k3s/master

# role comes from https://github.com/k3s-io/k3s-ansible
- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: master
  become: yes
  roles:
    - role: additional-netplan-ip
    - role: k3s-fix-master-node-ip
    - role: k3s-get-kubeconfig-local
    - role: k9s
    - role: helm3
    - role: yq

- hosts: master
  become: no
  roles:
    - role: tiny-tools-all-nodes
