---

- hosts: master
  gather_facts: yes
  become: no
  tags:
    - ingress

  roles:
    # primary and secondary nginx ingress
    - role: add_primary_nginx_ingress
    - role: add_secondary_nginx_ingress
