# https://docs.k3s.io/installation/configuration#configuration-file
# read by k3s at installation if it exists at /etc/rancher/k3s/config.yaml
kube-controller-manager-arg:
{% if k3s_version <= "v1.21" %}
- "address=0.0.0.0"
{% endif %}
- "bind-address=0.0.0.0"
kube-proxy-arg:
- "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
{% if k3s_version <= "v1.21" %}
- "address=0.0.0.0"
{% endif %}
- "bind-address=0.0.0.0"
{# advertise-address necessary with k3sv1.26, else worker node service fails because defaults to 127.0.0.1:6443 #}
{% if k3s_version > "v1.21" %}
kube-apiserver-arg:
- "advertise-address={{master_ip}}"
- "bind-address=0.0.0.0"
{% endif %}
etcd-expose-metrics: true
{% if kubelet_use_custom_dns %}
kubelet-arg:
- "resolv-conf=/etc/k3s-resolv.conf"
{% endif %}
flannel-backend: wireguard-native
